import Markdown from "react-markdown";

/** Chat text is untrusted, whether written by a player or generated by a model. */
export function ChatMessageBody({ text }: { text: string }) {
  return <div className="message-content">
    <Markdown components={{
      a({ href, children }) {
        // Keep app-local URLs and unsafe schemes out of model-authored navigation.
        if (!href || !/^https?:\/\//i.test(href)) return <span>{children}</span>;
        return <a href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
      },
      img({ alt }) {
        // Rendering an external image would issue a request without the user's action.
        return <span className="message-image-placeholder">[图片链接已隐藏{alt ? `：${alt.slice(0, 120)}` : ""}]</span>;
      },
    }}>{text}</Markdown>
  </div>;
}
